-- ---------------------------------------------------------------------------
-- Migration 008 — Tender themes (semantic-ish matching)
-- ---------------------------------------------------------------------------
--
-- Each tender carries 3-6 short FR themes generated by Claude Haiku at
-- scrape time. Used as additional matching signal in the scorer
-- (a profile keyword "rénovation" matches a tender with theme
-- "rénovation énergétique" even though the tender title only says
-- "Plan logement public").
--
-- GIN index so we can do array-overlap queries efficiently if we ever
-- expose theme filters in the UI ("Show me tenders tagged 'isolation'").
-- ---------------------------------------------------------------------------

alter table public.tenders
  add column if not exists themes text[]
  not null default '{}';

create index if not exists idx_tenders_themes
  on public.tenders using gin (themes);
